### ISSUE TITLE
Links to NED and NHD are broken

### ISSUE THREAD

**Issue by acrisci** [Ahlzen/TopOSM#5]
Links referenced in the readme to the required files for the USGS NED and USGS NHD data are broken. These links 404:

http://www.openstreetmap.us/nhd/
http://www.openstreetmap.us/ned/13arcsec/grid/

**Comment by Ahlzen** [comment]
Right, sorry about that. The data is still available on the old OSM-US servers, but there was a DNS change a while back that broke those links. I've updated the readme with the IP addresses of those servers for now. That should work.
